### ISSUE TITLE
Calculate mean temporal baseline of Timeseries

### ISSUE THREAD

**Issue by JackDMcGrath** [comet-licsar/licsbas#33]
Particularly after nullification, would probably be helpful if we could include a way of stating for each pixel what the mean baseline of all the IFGs that have data for it is

**Comment by espiritocz** [comment]
hi. the nullification is now updated and step 13 is recalculating the no-loop-ifg number (plus we keep number of nullified pixels), before calculating some other indices, including maxTlen. So this should include the information you propose?
please feel free to reopen and elaborate (=convince us that something more should be done here))
