### ISSUE TITLE
Bridge the dry season interferograms

### ISSUE THREAD

**Issue by DaisyUoE** [comet-licsar/licsbas#36]
Hi COMET, I am currently using the interferogram product from LiCS as input for LiCSBAS. To bridge the dry season interferograms, may I request the interferograms product to be reprocessed with spatio-temporal baselines parameters of 120 m and 14 months for a particular frame covering my study area please? Thank you in advance. -Daisy

**Comment by espiritocz** [comment]
hi Daisy,
not sure what do you mean by the 120 m spatial baseline, but the long ifgs make sense in specific areas. For communication/requests related to the LiCSAR data, please use the comet's form about 'frame requests' or direct email, both on the right pane of https://comet.nerc.ac.uk/COMET-LiCS-portal/
