### ISSUE TITLE
Installing LiCSBAS success but cannot run 

### ISSUE THREAD

**Issue by erlangga0909** [comet-licsar/licsbas#47]
Hi Morishita, 
Can you please help me with this error, I have already installed LiCSBAS 14.0 but I cannot figure out why the error comes from

![image](https://github.com/comet-licsar/LiCSBAS/assets/94942877/d17685c3-cd08-4e11-96b5-7becd9ce94be)

**Comment by y-okur** [comment]
I have the same problem. 

```
LiCSBAS01_get_geotiff.py Successfully finished!!

Output directory: /Volumes/HDD_OKUR2/061D_07906_131313/GEOC

Starting
Traceback (most recent call last):
  File "/Users/yagizalp/Documents/LiCSBAS/bin/LiCSBAS02_ml_prep.py", line 102, in <module>
    import LiCSBAS_plot_lib as plot_lib
  File "/Users/yagizalp/Documents/LiCSBAS/LiCSBAS_lib/LiCSBAS_plot_lib.py", line 49, in <module>
    import LiCSBAS_inv_lib as inv_lib
  File "/Users/yagizalp/Documents/LiCSBAS/LiCSBAS_lib/LiCSBAS_inv_lib.py", line 46, in <module>
    from scipy.sparse import csr_array, csc_array  # csr_matrix, csc_matrix # but maybe coo_matrix would be better for G? to be checked
ImportError: cannot import name 'csr_array'```

**Comment by espiritocz** [comment]
hi both. apologies, we somehow missed the messages (i expected email notifications that never happened).

anyway, there were more issues with the csr_array solution (that would be awesome if it worked) so we removed it at the end of September. Please check the latest Release (1.15.1), should not have such issues anymore.
