### ISSUE TITLE
 download issue

### ISSUE THREAD

**Issue by CUMT530849827** [comet-licsar/licsbas#51]
Download 124D_04854_171313.geo.hgt.tif
    HTTPError for 124D_04854_171313.geo.hgt.tif in 1th try
    HTTPError for 124D_04854_171313.geo.hgt.tif in 2th try
    HTTPError for 124D_04854_171313.geo.hgt.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/124/124D_04854_171313/metadata/124D_04854_171313.geo.hgt.tif

**Comment by pierreboymond** [comment]
I have the same issue with Frame 092A_08036_141719. Are the servers down?

Frame ID is 092A_08036_141719

Download 092A_08036_141719.geo.E.tif
    HTTPError for 092A_08036_141719.geo.E.tif in 1th try
    HTTPError for 092A_08036_141719.geo.E.tif in 2th try
    HTTPError for 092A_08036_141719.geo.E.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/92/092A_08036_141719/metadata/092A_08036_141719.geo.E.tif
Download 092A_08036_141719.geo.N.tif
    HTTPError for 092A_08036_141719.geo.N.tif in 1th try
    HTTPError for 092A_08036_141719.geo.N.tif in 2th try
    HTTPError for 092A_08036_141719.geo.N.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/92/092A_08036_141719/metadata/092A_08036_141719.geo.N.tif
Download 092A_08036_141719.geo.U.tif
    HTTPError for 092A_08036_141719.geo.U.tif in 1th try
    HTTPError for 092A_08036_141719.geo.U.tif in 2th try
    HTTPError for 092A_08036_141719.geo.U.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/92/092A_08036_141719/metadata/092A_08036_141719.geo.U.tif
Download 092A_08036_141719.geo.hgt.tif
    HTTPError for 092A_08036_141719.geo.hgt.tif in 1th try
    HTTPError for 092A_08036_141719.geo.hgt.tif in 2th try
    HTTPError for 092A_08036_141719.geo.hgt.tif in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/92/092A_08036_141719/metadata/092A_08036_141719.geo.hgt.tif

Download baselines
    HTTPError for baselines in 1th try
    HTTPError for baselines in 2th try
    HTTPError for baselines in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/92/092A_08036_141719/metadata/baselines
Download network.png
    HTTPError for network.png in 1th try
    HTTPError for network.png in 2th try
    HTTPError for network.png in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/92/092A_08036_141719/metadata/network.png
Download metadata.txt
    HTTPError for metadata.txt in 1th try
    HTTPError for metadata.txt in 2th try
    HTTPError for metadata.txt in 3th try
    Error while downloading from https://gws-access.jasmin.ac.uk/public/nceo_geohazards/LiCSAR_products/92/092A_08036_141719/metadata/metadata.txt

**Comment by CUMT530849827** [comment]
@pierreboymond It's working properly now  https://github.com/yumorishita/LiCSBAS2/issues/69

**Comment by nusretdemir** [comment]
The system is down.

**Comment by nusretdemir** [comment]
the system is down now

**Comment by nusretdemir** [comment]
The data still can not be downloaded.

**Comment by geomaticss** [comment]
its not working for now. 14 nov 2024.

**Comment by nusretdemir** [comment]
> The data still can not be downloaded.

Now working well. 15.11.2024

**Comment by geomaticss** [comment]
I think there are still some problems on the server side. It is a frame I have worked with before and there should be no problem with the relevant dates.

![image](https://github.com/user-attachments/assets/e4b13d7e-85e8-4ed7-b652-30964d9633b6)

**Comment by nusretdemir** [comment]
> I think there are still some problems on the server side. It is a frame I have worked with before and there should be no problem with the relevant dates.
> 
> ![image](https://private-user-images.githubusercontent.com/66463392/386493624-e4b13d7e-85e8-4ed7-b652-30964d9633b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTUyNTEsIm5iZiI6MTczMTY1NDk1MSwicGF0aCI6Ii82NjQ2MzM5Mi8zODY0OTM2MjQtZTRiMTNkN2UtODVlOC00ZWQ3LWI2NTItMzA5NjRkOTYzM2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA3MTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNzUzMDY3MDFiYThiM2I3NDU0YzQzZTc3YzEyODEwOWQ0MDYwNWRiNzZiYjg1YWE5YTIwZTM2ZWRkY2Q2NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L5s4kZ5Yw5yVn49ZxFOwAku5vMCZeARuD4rJvmz8C3g)

yes, same here..I have just realized it at my case too

**Comment by geomaticss** [comment]
> > I think there are still some problems on the server side. It is a frame I have worked with before and there should be no problem with the relevant dates.
> > ![image](https://private-user-images.githubusercontent.com/66463392/386493624-e4b13d7e-85e8-4ed7-b652-30964d9633b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTUyNTEsIm5iZiI6MTczMTY1NDk1MSwicGF0aCI6Ii82NjQ2MzM5Mi8zODY0OTM2MjQtZTRiMTNkN2UtODVlOC00ZWQ3LWI2NTItMzA5NjRkOTYzM2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA3MTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNzUzMDY3MDFiYThiM2I3NDU0YzQzZTc3YzEyODEwOWQ0MDYwNWRiNzZiYjg1YWE5YTIwZTM2ZWRkY2Q2NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L5s4kZ5Yw5yVn49ZxFOwAku5vMCZeARuD4rJvmz8C3g)
> 
> yes, same here..I have just realized it at my case too

I still get the error downloading the data. is your problem persisting?

**Comment by nusretdemir** [comment]
> > > I think there are still some problems on the server side. It is a frame I have worked with before and there should be no problem with the relevant dates.
> > > ![image](https://private-user-images.githubusercontent.com/66463392/386493624-e4b13d7e-85e8-4ed7-b652-30964d9633b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTUyNTEsIm5iZiI6MTczMTY1NDk1MSwicGF0aCI6Ii82NjQ2MzM5Mi8zODY0OTM2MjQtZTRiMTNkN2UtODVlOC00ZWQ3LWI2NTItMzA5NjRkOTYzM2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA3MTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNzUzMDY3MDFiYThiM2I3NDU0YzQzZTc3YzEyODEwOWQ0MDYwNWRiNzZiYjg1YWE5YTIwZTM2ZWRkY2Q2NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L5s4kZ5Yw5yVn49ZxFOwAku5vMCZeARuD4rJvmz8C3g)
> > 
> > 
> > yes, same here..I have just realized it at my case too
> 
> I still get the error downloading the data. is your problem persisting?

yes same.. They have published an announcement here  https://comet.nerc.ac.uk/

**Comment by espiritocz** [comment]
December update - the disk storage seems stable for now, but as there were more such events this year, we cannot say for sure in future. We communicate with our partners and prepare an improved solution, yet no news at this moment. Hope the disk will remain stable..
