### ISSUE TITLE
并行处理IFG到后面一直停留，毫无反应？

### ISSUE THREAD

**Issue by Lijuming33** [comet-licsar/licsbas#53]
`python LiCSBAS02_m1_prep.py -i GEOC -n 1`
执行程序最后面卡住不动，这是什么情况？
![微信图片_20240923122843](https://github.com/user-attachments/assets/ad198886-1097-474e-84e3-9a3e3f53db75)

![微信图片_20240923122623](https://github.com/user-attachments/assets/7cf66f45-0e16-46e5-bcaa-3df086ee1eb1)

**Comment by ditafaith** [comment]
Hi @Lijuming33, you can re-run the command.

**Comment by espiritocz** [comment]
please communicate in English with us.
