### ISSUE TITLE
LiCSBAS Binder error 

### ISSUE THREAD

**Issue by firmanhadi** [comet-licsar/licsbas#58]
Hi all,

I want to use LiCSBAS Binder version for teaching.
When I ran this cell: `LiCSBAS01_get_geotiff.py -f 127A_09749_121312 -s 20230101 -e 20230331 --get_gacos --n_para 1 `
I got an error : 
```
Cell In[10], line 2
    LiCSBAS01_get_geotiff.py -f 127A_09749_121312 -s 20230101 -e 20230331 --get_gacos --n_para 1
                                  ^
SyntaxError: invalid decimal literal
```
Any help would be very much appreciated.
Thanks.

**Comment by espiritocz** [comment]
you forgot adding '!' in the beginning of the line as in the tutorial ipynb. Jupyter ntb runs python by default, unless you set by '!' that this is a bash command.
